name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.9]

    steps:
      - uses: actions/checkout@v2

      - name: Use Bun.js Latest
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies & build
        run: |
          bun install
          bun run build          

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}